services:
  backend-web:
    image: nginx:latest
    container_name: doctors-backend-web
    volumes:
      - ./doctors-portal-backend:/var/www
      - ./doctors-portal-backend/docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      php-fpm:
        condition: service_started
    networks:
      - doctors-network

  php-fpm:
    build:
      context: ./doctors-portal-backend
      dockerfile: Dockerfile.prod
    container_name: doctors-backend-php
    volumes:
      - ./doctors-portal-backend:/var/www
    networks:
      - doctors-network

  mysql:
    image: mysql:8.0
    container_name: doctors-mysql
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Hailtotheking!1
      MYSQL_DATABASE: doctors-portal
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - doctors-network

  # frontend:
  #   build:
  #     context: ./doctors-portal-frontend
  #     dockerfile: Dockerfile.dev
  #   container_name: doctors-frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./doctors-portal-frontend:/app
  #   networks:
  #     - doctors-network
  #   command: sh -c "npm install && npx vite --host"

  frontend:
    build:
      context: ./doctors-portal-frontend
      dockerfile: Dockerfile.prod
    container_name: doctors-frontend
    ports:
      - "8080:80"
    networks:
      - doctors-network


volumes:
  mysql-data:

networks:
  doctors-network:
