services:
  frontend:
    build:
      context: .  # <- use . if Dockerfile is in the same folder as package.json
      dockerfile: Dockerfile
    ports:
      - "5173:8080"
    networks:
      - laravel-development

networks:
  laravel-development:
